Repository parlemonde/1village, pull requests merged in 2022-09, with the labels that each got.

#422 fix #197 : Proposition of LightBox for the images
  src/components/activities/ActivityView/DefiActivityView.tsx
  src/components/activities/ActivityView/MascotteActivityView.tsx
  src/components/activities/ActivityView/StoryActivityView.tsx
  src/components/activities/content/editors/ImageEditor/ImageModal.tsx
  src/components/activities/content/views/ImageView.tsx
  src/components/lightbox/Lightbox.tsx
  src/pages/contenu-libre/2.tsx
Labels: Done

#420 video access riddle added
  src/components/accueil/VideoPresentation.tsx
Labels: awaiting testing

#435 427 lateral menu
  src/components/Avatar.tsx
  src/components/Navigation.tsx
  src/components/activities/utils.ts
Labels: awaiting review

#436 change(#429): Right menu change for Pelico user
  src/components/accueil/RightNavigation.tsx
Labels: awaiting testing

#417 comment and reaction disabled for Observator
  src/components/activities/ActivityComments/AddComment.tsx
  src/pages/creer-un-jeu/mimique/4.tsx
  src/pages/creer-une-enigme/4.tsx
  src/pages/creer-une-histoire/5.tsx
  src/pages/indice-culturel/3.tsx
  src/pages/lancer-un-defi/culinaire/4.tsx
  src/pages/lancer-un-defi/ecologique/4.tsx
  src/pages/lancer-un-defi/linguistique/5.tsx
  src/pages/mascotte/5.tsx
  src/pages/poser-une-question/3.tsx
  src/pages/re-inventer-une-histoire/5.tsx
  src/pages/reagir-a-une-activite/3.tsx
  src/pages/realiser-un-reportage/3.tsx
  src/pages/se-presenter/thematique/4.tsx
  src/pages/symbole/3.tsx
Labels: awaiting testing

#424 fix(cards): Link to activity was missing in StoryCard and MascotteCard
  src/components/activities/ActivityCard/MascotteCard.tsx
  src/components/activities/ActivityCard/StoryCard.tsx
Labels: awaiting testing

#439 change(#427) : Link change for mascotte depending if created or not
  src/components/Navigation.tsx
Labels: awaiting testing

#418 414 modification touchant à laccessibilité des mascottes
  __mocks__/svg.js
  next.config.js
  package.json
  src/components/WorldMap/WorldMap.tsx
  src/components/activities/__tests__/defiChecksCooking.test.tsx
  src/components/activities/__tests__/getActivityPhase_Mascotte.test.tsx
  src/components/activities/__tests__/getActivityPhase_Presentation.test.tsx
  src/components/activities/mascotteChecks.tsx
  src/components/activities/utils.ts
  src/contexts/activityContext.tsx
  src/contexts/villageContext.tsx
  src/pages/chanter-un-couplet/index.tsx
  src/pages/contenu-libre/index.tsx
  src/pages/creer-un-jeu/mimique/1.tsx
  src/pages/creer-une-enigme/1.tsx
  src/pages/creer-une-histoire/1.tsx
  src/pages/indice-culturel/1.tsx
  src/pages/lancer-un-defi/culinaire/1.tsx
  src/pages/lancer-un-defi/ecologique/1.tsx
  src/pages/lancer-un-defi/linguistique/1.tsx
  src/pages/mascotte/1.tsx
  src/pages/mascotte/5.tsx
  src/pages/parametrer-hymne/1.tsx
  src/pages/poser-une-question/1.tsx
  src/pages/poser-une-question/3.tsx
  src/pages/re-inventer-une-histoire/index.tsx
  src/pages/reagir-a-une-activite/1.tsx
  src/pages/realiser-un-reportage/1.tsx
  src/pages/se-presenter/thematique/1.tsx
  src/pages/symbole/1.tsx
  src/services/useImagesStory.ts
  tsconfig.json
  types/phase.type.ts
Labels: Feedback

#440 add(#303): cursor pointer missing added to Enigme and Story Cards
  src/components/activities/ActivityCard/EnigmeCard.tsx
  src/components/activities/ActivityCard/StoryCard.tsx
Labels: awaiting testing

#446 change(video): New video added to homepage
  src/components/accueil/VideoPresentation.tsx
Labels: awaiting review

#447 change(comment): PelicoNeutre to replace flag when user is Pelico in …
  src/components/activities/ActivityComments/CommentCard.tsx
Labels: awaiting review
