Repository parlemonde/1village, pull requests merged in 2025-09, with the labels that each got.

#1090 feat(VIL-791): delete unused code (symbols were merged into indice category)
  src/activity-types/activity.constants.ts
  src/activity-types/activity.constants.tsx
  src/activity-types/anyActivity.ts
  src/activity-types/symbol.constants.ts
  src/activity-types/symbol.types.ts
  src/components/Navigation.tsx
  src/components/activities/ActivityCard/SymbolCard.tsx
  src/components/activities/ActivityCard/index.tsx
  src/components/activities/ActivityView/index.tsx
  src/components/activities/__tests__/getActivityPhase_utils.test.tsx
  src/components/activities/utils.ts
  src/config/mediatheque/dataFilters.ts
  src/pages/activite/[id].tsx
  src/pages/indice-culturel/index.tsx
  src/pages/symbole/1.tsx
  src/pages/symbole/2.tsx
  src/pages/symbole/3.tsx
  src/pages/symbole/index.tsx
  src/pages/symbole/success.tsx
  src/svg/indice-culturel/animal-national.svg
  src/svg/indice-culturel/devise.svg
  src/svg/indice-culturel/drapeau.svg
  src/svg/indice-culturel/embleme.svg
  src/svg/indice-culturel/figure-symbolique.svg
  src/svg/indice-culturel/fleur-nationale.svg
  src/svg/indice-culturel/hymne.svg
  src/svg/indice-culturel/monnaie.svg
  src/svg/navigation/symbol-icon.svg
  types/activity.type.ts
Labels: 7. Résolu

#1089 feat(VIL-711): graphique de contributions des classes
  server/controllers/statistics/statistics.ts
  server/stats/classroomStats.ts
  src/components/admin/dashboard-statistics/VillageStats.tsx
  src/components/admin/dashboard-statistics/cards/ClassesContributionCard/ClassesContributionCard.module.css
  src/components/admin/dashboard-statistics/cards/ClassesContributionCard/ClassesContributionCard.tsx
  src/components/admin/dashboard-statistics/cards/ClassesExchangesCard/ClassesExchangesCard.module.css
  src/components/admin/dashboard-statistics/charts/ContributionBarChart.tsx
  src/components/admin/dashboard-statistics/dashboard-summary/DashboardClassroomTab.tsx
  src/components/admin/dashboard-statistics/mocks/mocks.ts
  src/components/admin/dashboard-statistics/styles/charts.module.css
  types/dashboard.type.ts
  types/statistics.type.ts
Labels: 5. Résolu, 4.2. Testé et validé sur staging, 3.2. Review validée

#1104 feat/VIL-814: Filter the number of child codes created
  server/stats/queryStatsByFilter.ts
Labels: 5. Résolu, 4.2. Testé et validé sur staging

#1109 feat(VIL-820) update pelico
  src/components/activities/ActivityCard/FreeContentCard.tsx
Labels: 4.2. Testé et validé sur staging, 3.2. Review validée

#1111 feat(VIL-823): change the order of activities in phase 1
  src/components/Navigation.tsx
Labels: 4.2. Testé et validé sur staging, 3.2. Review validée
